### ISSUE TITLE
Reproduction of the results from the paper

### ISSUE THREAD

**Issue by ksachdeva** [paudan/TimeNet#2]
Hi @paudan 

Very nice work and clean code.

I was wondering whether you were able to reproduce the results from the paper using your implementation.

Also, feather files in the data folder are just an example of the 18 datasets the authors used in the paper. I saw the code to make the feather files but am not sure if the files in the repo are the final generated files or just a subset as an example.

Regards & thanks
Kapil

**Comment by paudan** [comment]
Hi @ksachdeva,

unfortunately, I failed to reproduce the results, as the original paper does not describe t-SNE parameters, data preprocessing steps, or the whole specificity of the TF implementation. It does not clearly address processing time series with non-uniform lengths as well. Hence, I added my own extensions here

The data files that I provided in the repo are the ones that I used during development, except the test file which is quite large (over 300 MB); yet the code can be used to reproduce it. I tried to follow the guidelines in the paper to select data matching the subset used in the experiment as closely as possible.

Any improvements and suggestions are welcome!

**Comment by ksachdeva** [comment]
Thanks, @paudan for the quick reply. Much appreciated.

I figured this must have been the reason. Your code is very clean and nicely written. I may send a pull request and/or build on it to see if I can reproduce the results. 

Regards
Kapil
